[WIP] Place matching docs
radarlabs/documentation pull request #146
Opened 2022-06-13 21:42 UTC by jsani-radar

Docs for Place matching launch

![place_matching](https://user-images.githubusercontent.com/58698757/173450208-6e68bac6-3ec2-403d-bedc-2ddcae43f527.gif)

2022-06-13 22:01 UTC, bschoeneweis requested changes
Looks great!  Few small nits, love the gif though.  This will definitely help guide usage 🙌

2022-06-13 22:01 UTC, bschoeneweis commented on docs/dashboard.mdx
> +Place matching is the simplest way to clean your geofence datasets while making sure they stay up-to-date and accurate over time. Navigate to the [Geofences](https://radar.com/dashboard/geofences) pa
nit: seems like `Geofences` is capitalized as a context type but `places` generally are not.  May want to make these consistent.  Can ignore if this is the precedent across the docs site already

2022-06-14 12:07 UTC, corypisano approved these changes
lgtm after bradley's comments

2022-06-14 12:07 UTC, corypisano commented on docs/dashboard.mdx
> +1. **Import your Geofences against Radar's places data.** Upon importing your geofences into Radar, select [chains](/places/chains) to match your geofences aganist. By default, Radar will search for
do we want to mentioned re: search radius that it will match to the closest one within 10 km

2022-06-14 18:37 UTC, bschoeneweis approved these changes
Looks great!

2022-06-15 03:42 UTC, merged