Document debug logging listeners
radarlabs/documentation pull request #168
Opened 2022-08-15 20:40 UTC by jsani-radar

follow-up from @palmakkar's onboarding that we don't document the debug log message listeners

2022-08-15 20:44 UTC, jsani-radar commented
<img width="957" alt="Screen Shot 2022-08-15 at 4 43 25 PM" src="https://user-images.githubusercontent.com/58698757/184715071-a84e6b77-b744-4670-aaa5-2cc39a3d79a9.png">

<img width="954" alt="Screen Shot 2022-08-15 at 4 43 48 PM" src="https://user-images.githubusercontent.com/58698757/184715090-8b0605b8-6e93-4e28-ba7c-4eebc7eee3a5.png">

2022-08-15 20:51 UTC, jrtibbetts requested changes
Just one small change for the Objective-C example.

2022-08-15 20:51 UTC, jrtibbetts commented on docs/sdk/ios.mdx
> +- (void)didLog:(NSString *)message {
`- (void)didLogMessage:(NSString *_Nonnull)message {`

2022-08-15 20:57 UTC, jsani-radar commented on docs/sdk/ios.mdx
> +- (void)didLog:(NSString *)message {
hmm it doesn't seem like we add this annotation for any of the other listeners - what's the benefit / drawback of including / not including it

2022-08-18 16:22 UTC, jrtibbetts commented on docs/sdk/ios.mdx
> +- (void)didLog:(NSString *)message {
It's fine to leave out the `_Nonnull`, but the user may get a compiler warning for it. But the signature _does_ have to be `didLogMessage`, not just `didLog`.

2022-08-18 16:34 UTC, jrtibbetts approved these changes

2022-08-18 18:18 UTC, merged