analytics v2
radarlabs/documentation pull request #30
Opened 2021-07-24 00:12 UTC by david-goodfellow

## What?

## Why?

## How?

## Screenshots (optional)

## Anything Else? (optional)

2021-07-26 01:26 UTC, jsani-radar commented
Can we get a clubhouse / screenshot / launch date included here?

Want to see how the page looks before it goes

2021-07-26 16:14 UTC, david-goodfellow commented
![image](https://user-images.githubusercontent.com/61531269/127022909-09523b1f-f416-4270-ae77-83dac67888e9.png)
![image](https://user-images.githubusercontent.com/61531269/127022920-b684999e-2bf6-43ad-8992-c0fed58e923c.png)

2021-07-26 16:15 UTC, david-goodfellow commented
https://app.clubhouse.io/radarlabs/story/6765/analytics-v2-documentation

2021-07-26 21:16 UTC, aidancleary commented on docs/trip-tracking.mdx
> +- **`Repeat customers`**: the total number of your users who have completed more than one trip.
Shouldn't this read:
Repeat customers: the total number of users who have completed more than one trip. Like the other statistic cards, the number of repeat customers is affected by the filters set in the Filters section.

2021-07-26 21:19 UTC, aidancleary commented on docs/trip-tracking.mdx
> +The Filters button at the top of the page offers you ways to look at more granular views of your trip data. The filters set with this button apply to the statistics cards and graphs as well as the da
delete "you", so it just says "offers ways to look at more.."

2021-07-26 21:22 UTC, aidancleary commented on docs/trip-tracking.mdx
> +**Date Range:** Select a date from the drop-down date picker. Make sure that the date in the left-hand box falls before the date in the right-hand box. (The default date range when first accessing th
I think change this to:

> Date Range: A date range can be selected from the drop-down date picker. Make sure that the date in the left-hand box falls before the date in the right-hand box. When accessing the Analytics page, the default date range encompasses all trip data in your project, meaning that you'll see a default range from the date of your earliest trip to yesterday. All trip analytics are updated nightly and trip analytics from today will not be shown in the Analytics page until tomorrow.

2021-07-26 21:25 UTC, aidancleary requested changes
made 3 small edits

2021-07-27 01:58 UTC, jsani-radar reviewed
looking solid overall, may seem like a lot of comments but mostly just want to condense language to streamline things / make it easier to scan

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +### Statistic cards
let's come up with a better header here, this is gonna be on the right sidebar - maybe "Trip metrics" or just "Metrics"?

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +Radar offers analytics on trip data and location opt-in rates from users in your project. [Analytics](https://radar.io/dashboard/analytics) on trip data can be found on the Analytics page and grouped
**for** users in your project. Let's hyperlink users with https://radar.io/documentation/api#users as well

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +The Filters button at the top of the page offers you ways to look at more granular views of your trip data. The filters set with this button apply to the statistics cards and graphs as well as the da
Remove "set with this button" so the second sentence reads "The filters will apply to the statistics cards..."

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +**Date Range:** Select a date from the drop-down date picker. Make sure that the date in the left-hand box falls before the date in the right-hand box. (The default date range when first accessing th
do we have validation around the left hand / right hand constraint? fine if not, but feels like a common pattern, which would reduce a sentence here

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +- **`Median wait time`**: the median duration of time that it takes between the moment when a user arrives at a destination (`user.arrived_at_trip_destination`) and the moment when the trip is marked
singular: `statistic`, or `metric` depending on previous convo

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +- **`Number of trips`**: the total count of all trips for a specific project which is live and has a status of `completed`.
instead of "which is live" can we we put "live" in between "all trips"

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +- **`Median trip time`**: the median duration of time that it takes between the moment when the user starts a trip (`user.started_trip`) and the moment when they arrive at the destination (`user.arri
remove "of the time that it takes" so it reads "the median duration between"

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +- **`Repeat customers`**: the total number of your users who have completed more than one trip. (like the other statistic cards, the number of repeat customers is affected by the filters set in the F
"total number of users", do we need the parenthesis statement here?

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +The graphs for each card show the change over time in each statistic. The time windows of each graph are automatically determined by the dates set in the Filters button. To see data grouped by hour,
should we have a chart to see the correspondence between # of days / grouping? feels like that'd be easier to grok

Last ___ Days | Grouping
2                     | Hour
21                   | Day
60                  | Week
60+                | Month

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +The By Destination table groups your trip data by individual destination geofence and allows you to identify your slowest and fastest stores by wait time as well as your most popular stores by the nu
can we bold "slowest and fastest stores" / "popular stores"

2021-07-27 01:58 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +By default, the By Destination table is sorted alphabetically based on the Destination column. Clicking on any column header will sort the table by that column's metrics in ascending order. To sort t
To toggle the sort order of the column, click the column header.

2021-07-27 02:00 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +### Statistic cards
let's come up with a better header here, this is gonna be on the right sidebar - maybe "Trip metrics" or just "Metrics"?

2021-07-27 14:45 UTC, david-goodfellow commented on docs/trip-tracking.mdx
> +- **`Repeat customers`**: the total number of your users who have completed more than one trip. (like the other statistic cards, the number of repeat customers is affected by the filters set in the F
defer to @aidancleary

2021-07-27 14:57 UTC, david-goodfellow commented on docs/trip-tracking.mdx
> +- **`Repeat customers`**: the total number of your users who have completed more than one trip.
Took out the parenthesis based on @jsani-radar [comment](https://github.com/radarlabs/documentation/pull/30#discussion_r677057573)

2021-07-27 14:58 UTC, david-goodfellow commented on docs/trip-tracking.mdx
> +### Statistic cards
@aidancleary made the switch to trip metrics but want your input

2021-07-27 17:11 UTC, jsani-radar approved these changes
few small nits, overall looks good - let's confirm "Trip metrics" as the top-level header before merging this in

2021-07-27 17:11 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +| Last ___ Days  | Time Grouping |
let's get an updated screenshot? I'm thinking the ___ won't look too great, maybe "Number of Days" as the column header?

2021-07-27 17:11 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +The By Destination table groups your trip data by individual destination geofence and allows you to identify your **slowest and fastest stores** by wait time as well as your most popular stores by th
bold "most popular stores"

2021-07-27 17:11 UTC, jsani-radar commented on docs/trip-tracking.mdx
> +The graphs for each card show the change over time in each statistic. The time windows of each graph are automatically determined by the dates set in the Filters button. To see data grouped by hour,
think we can remove the last 4 sentences since we now have this table

2021-07-27 17:19 UTC, david-goodfellow commented
![image](https://user-images.githubusercontent.com/61531269/127199065-f142f45b-84c8-4275-a970-9e3468bcc5af.png)

2021-07-27 18:56 UTC, aidancleary commented on docs/trip-tracking.mdx
> +- **`Repeat customers`**: the total number of your users who have completed more than one trip. (like the other statistic cards, the number of repeat customers is affected by the filters set in the F
Ah, i wrote "This statistics omits trips..." , need to delete the last S in statistics for both 'median wait time' and 'median trip time'

2021-07-27 18:58 UTC, aidancleary commented on docs/trip-tracking.mdx
> +### Statistic cards
we should call it "Trips Overview" since that's what the header is for the section here

2021-07-27 19:02 UTC, aidancleary commented
on line 142 can we change "Trip stats" to "Trip analytics"

2021-07-27 20:22 UTC, merged