docs for lifecycle logs
radarlabs/documentation pull request #427
Opened 2024-01-03 19:36 UTC by KennyHuRadar

## What?

## Why?

## How?

## Screenshots (optional)

## Anything Else? (optional)

2024-01-03 20:26 UTC, lmeier requested changes

2024-01-03 20:26 UTC, lmeier commented on docs/sdk/android.mdx
> +Unlike IOS, app lifecycle events will be logged without the additional setup.
`iOS` instead of `IOS`.

But maybe let's roll with "The Android SDK automatically logs lifecycle events without the additional required on iOS."

2024-01-03 20:26 UTC, lmeier commented on docs/sdk/ios.mdx
> +Note that additional setup is required in the `AppDelegate` to log app lifecycle events.
"Logging app lifecycle events requires adding calls to Radar methods in the `AppDelegate` lifecycle methods."

2024-01-03 20:26 UTC, lmeier commented on docs/sdk/ios.mdx
> +    // other code
Let's say "// existing code" instead of "other code" here and in all 6 instances here.

2024-01-03 20:26 UTC, lmeier commented on docs/sdk/react-native.mdx
> +App lifecycle events are logged natively. No setup is required for the Android SDK while IOS instructions can be found in the [iOS SDK documentation](/sdk/ios).
The first sentence could lead people to not really grasp in the second that they need to do something.

"Logging app lifecycle events is done in platform native code. Instructions for doing so on iOS can be found [here](documentation/sdk/ios#debug-logging). App lifecycle event on Android happens automatically without any additional setup."

Make sure to verify that link goes correctly to the debug logging part of the ios documentation as well.

2024-01-03 20:27 UTC, jsani-radar reviewed
few small comments, will be 👍🏽 on next pass

2024-01-03 20:27 UTC, jsani-radar commented on docs/sdk/android.mdx
> +Unlike IOS, app lifecycle events will be logged without the additional setup.
don't think we need to call out iOS here - "App lifecycle events are logged by default" should be good enough

2024-01-03 20:27 UTC, jsani-radar commented on docs/sdk/ios.mdx
> +Note that additional setup is required in the `AppDelegate` to log app lifecycle events.
it'd be good to have a 1-sentence summary of the changes necessary - for example, "Your `AppDelegate` needs to conform to `RadarDelegate`" or something of the sort

2024-01-03 20:27 UTC, jsani-radar commented on docs/sdk/react-native.mdx
> +App lifecycle events are logged natively. No setup is required for the Android SDK while IOS instructions can be found in the [iOS SDK documentation](/sdk/ios).
typo: IOS --> iOS

let's also link out to the specific anchor with the app lifecycle logging `#debug-logging`

2024-01-03 20:27 UTC, jsani-radar commented on docs/sdk/ios.mdx
> +  // other code
discussed offline - `// existing code`

2024-01-03 20:43 UTC, KennyHuRadar commented on docs/sdk/android.mdx
> +Unlike IOS, app lifecycle events will be logged without the additional setup.
The rationale is to prevent people who are implementing both platforms to think that the android instructions are missing. Do you think its not worth having?

2024-01-03 21:07 UTC, lmeier approved these changes
2 small nits, then LGTM

2024-01-03 21:07 UTC, lmeier commented on docs/sdk/ios.mdx
> +To log app lifecycle events, call following Radar methods in the `AppDelegate` lifecycle methods:
"call the respective Radar methods" instead of "call following Radar methods"

2024-01-03 21:07 UTC, lmeier commented on docs/sdk/react-native.mdx
> +Logging app lifecycle events is done in platform native code. Instructions for doing so on iOS can be found  in the [iOS SDK documentation](/sdk/ios#debug-logging). App lifecycle event on Android hap
extra space between "found" and "in"

2024-01-03 21:09 UTC, jsani-radar commented on docs/sdk/ios.mdx
> +<a id="debug-logging"></a>
don't think this is needed - the anchor comes for free with the h2
<img width="527" alt="Screenshot 2024-01-03 at 4 09 30 PM" src="https://github.com/radarlabs/documentation/assets/58698757/a4bda578-ba68-45cf-a61a-c3a66fbdebff">

2024-01-03 21:10 UTC, jsani-radar commented on docs/sdk/react-native.mdx
> +Logging app lifecycle events is done in platform native code. Instructions for doing so on iOS can be found  in the [iOS SDK documentation](/sdk/ios#debug-logging). App lifecycle event on Android hap
also pluralize "events" in the last sentence

2024-01-04 18:37 UTC, lmeier commented
@jsani-radar I don't have authorization to merge this. Mind taking a look and proceeding if everything LGTU?

2024-01-04 18:38 UTC, jsani-radar commented
will take a pass and merge - thanks for the heads up

2024-01-04 20:25 UTC, jsani-radar approved these changes

2024-01-04 20:25 UTC, merged